// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Task struct {
	ID           int32          `json:"id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	Completed    sql.NullBool   `json:"completed"`
	Creationdate sql.NullTime   `json:"creationdate"`
	Duedate      sql.NullTime   `json:"duedate"`
}
